PREFIX : <http://askomics.org/data/>
PREFIX askomics: <http://askomics.org/internal/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX faldo: <http://biohackathon.org/resource/faldo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?FIELD_ID1_Label ?PLOT_ID_ANNUAL1_Label ?YIELDS42_DRY_WEIGHT_1000_SEEDS ?YIELDS42_DRY_WEIGHT
WHERE {
    ?PLOT_ID_ANNUAL11_uri <http://askomics.org/data/plot_of> ?FIELD_ID1_uri .
    ?YIELDS42_uri <http://askomics.org/data/yield_sample_of> ?PLOT_ID_ANNUAL11_uri .
    ?FIELD_ID1_uri rdf:type <http://askomics.org/data/FIELD_ID> .
    ?FIELD_ID1_uri rdfs:label ?FIELD_ID1_Label .
    ?FIELD_ID1_uri <http://askomics.org/data/CAMPAIGN> ?FIELD_ID1_CAMPAIGNCategory .
    ?PLOT_ID_ANNUAL11_uri rdf:type <http://askomics.org/data/PLOT_ID_ANNUAL> .
    ?PLOT_ID_ANNUAL11_uri rdfs:label ?PLOT_ID_ANNUAL1_Label .
    ?YIELDS42_uri rdf:type <http://askomics.org/data/YIELDS> .
    ?YIELDS42_uri <http://askomics.org/data/DRY_WEIGHT_1000_SEEDS> ?YIELDS42_DRY_WEIGHT_1000_SEEDS .
    ?YIELDS42_uri <http://askomics.org/data/DRY_WEIGHT> ?YIELDS42_DRY_WEIGHT .


    VALUES ?FIELD_ID1_CAMPAIGNCategory { <http://askomics.org/data/Y2> }
}
