PREFIX : <http://askomics.org/data/>
PREFIX askomics: <http://askomics.org/internal/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX faldo: <http://biohackathon.org/resource/faldo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?FIELD_ID1_Label ?FIELD_ID1_CAMPAIGN ?LOCATION1_REGION ?AGRICULTURE1_SOIL_MANAGMENT ?AGRICULTURE1_CROP ?AGRICULTURE1_AGRI_TYPE ?FIELD_SUB_ID1_SEASON ?PLOT_ID_SEASONAL1_Label ?BIOAGRESSORS_LAB1_PLANT_DEVELOPMENT_STAGE ?BIOAGRESSORS_LAB1_OVERALL_FOLIAR_PARASITISM ?BIOAGRESSORS_LAB1_OVERALL_FOLIAR_PHYTOPHAGY ?BIOAGRESSORS_LAB1_PLANT ?BIOAGRESSORS_LAB1_MYCOSPHAERELLA_GRAMINICOLA ?BIOAGRESSORS_LAB1_DELIA_RADICUM ?BIOAGRESSORS_LAB82_NUMBER_OF_STEMS ?BIOAGRESSORS_LAB1_PLASMODIOPHORA_BRASSICAE ?BIOAGRESSORS_LAB82_NUMBER_OF_STEMS_PER_PLANT ?BIOAGRESSORS_LAB1_FUSARIUM_GRAMINEARUM ?BIOAGRESSORS_LAB1_PYRENOPEZZIZA_BRASSICAE ?BIOAGRESSORS_LAB1_PUCCINIA_RECONDITA ?BIOAGRESSORS_LAB82_NUMBER_OF_LIVING_LEAVES ?BIOAGRESSORS_LAB82_PLANT_HEIGHT ?BIOAGRESSORS_LAB1_SCAPTOMYZA_FLAVA
WHERE {
    ?LOCATION5_uri <http://askomics.org/data/location_of> ?FIELD_ID1_uri .
    ?AGRICULTURE30_uri <http://askomics.org/data/agriculture_of> ?FIELD_ID1_uri .
    ?FIELD_SUB_ID59_uri <http://askomics.org/data/season_of> ?FIELD_ID1_uri .
    ?PLOT_ID_SEASONAL66_uri <http://askomics.org/data/plot_of> ?FIELD_SUB_ID59_uri .
    ?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/bioagressors_lab_sample_of> ?PLOT_ID_SEASONAL66_uri .
    ?FIELD_ID1_uri rdf:type <http://askomics.org/data/FIELD_ID> .
    ?FIELD_ID1_uri rdfs:label ?FIELD_ID1_Label .
    ?FIELD_ID1_uri <http://askomics.org/data/CAMPAIGN> ?FIELD_ID1_CAMPAIGNCategory .
    ?FIELD_ID1_CAMPAIGNCategory rdfs:label ?FIELD_ID1_CAMPAIGN .
    ?LOCATION5_uri rdf:type <http://askomics.org/data/LOCATION> .
    ?LOCATION5_uri <http://askomics.org/data/REGION> ?LOCATION5_REGIONCategory .
    ?LOCATION5_REGIONCategory rdfs:label ?LOCATION1_REGION .
    ?AGRICULTURE30_uri rdf:type <http://askomics.org/data/AGRICULTURE> .
    OPTIONAL {?AGRICULTURE30_uri <http://askomics.org/data/SOIL_MANAGMENT> ?AGRICULTURE30_SOIL_MANAGMENTCategory .
        OPTIONAL {?AGRICULTURE30_SOIL_MANAGMENTCategory rdfs:label ?AGRICULTURE1_SOIL_MANAGMENT .}}
    OPTIONAL {?AGRICULTURE30_uri <http://askomics.org/data/CROP> ?AGRICULTURE30_CROPCategory .
        OPTIONAL {?AGRICULTURE30_CROPCategory rdfs:label ?AGRICULTURE1_CROP .}}
    OPTIONAL {?AGRICULTURE30_uri <http://askomics.org/data/AGRI_TYPE> ?AGRICULTURE30_AGRI_TYPECategory .
        OPTIONAL {?AGRICULTURE30_AGRI_TYPECategory rdfs:label ?AGRICULTURE1_AGRI_TYPE .}}
    ?FIELD_SUB_ID59_uri rdf:type <http://askomics.org/data/FIELD_SUB_ID> .
    ?FIELD_SUB_ID59_uri <http://askomics.org/data/SEASON> ?FIELD_SUB_ID59_SEASONCategory .
    ?FIELD_SUB_ID59_SEASONCategory rdfs:label ?FIELD_SUB_ID1_SEASON .
    ?PLOT_ID_SEASONAL66_uri rdf:type <http://askomics.org/data/PLOT_ID_SEASONAL> .
    ?PLOT_ID_SEASONAL66_uri rdfs:label ?PLOT_ID_SEASONAL1_Label .
    ?BIOAGRESSORS_LAB82_uri rdf:type <http://askomics.org/data/BIOAGRESSORS_LAB> .
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/PLANT_DEVELOPMENT_STAGE> ?BIOAGRESSORS_LAB82_PLANT_DEVELOPMENT_STAGECategory .
        OPTIONAL {?BIOAGRESSORS_LAB82_PLANT_DEVELOPMENT_STAGECategory rdfs:label ?BIOAGRESSORS_LAB1_PLANT_DEVELOPMENT_STAGE .}}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/OVERALL_FOLIAR_PARASITISM> ?BIOAGRESSORS_LAB82_OVERALL_FOLIAR_PARASITISMCategory .
        OPTIONAL {?BIOAGRESSORS_LAB82_OVERALL_FOLIAR_PARASITISMCategory rdfs:label ?BIOAGRESSORS_LAB1_OVERALL_FOLIAR_PARASITISM .}}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/OVERALL_FOLIAR_PHYTOPHAGY> ?BIOAGRESSORS_LAB82_OVERALL_FOLIAR_PHYTOPHAGYCategory .
        OPTIONAL {?BIOAGRESSORS_LAB82_OVERALL_FOLIAR_PHYTOPHAGYCategory rdfs:label ?BIOAGRESSORS_LAB1_OVERALL_FOLIAR_PHYTOPHAGY .}}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/PLANT> ?BIOAGRESSORS_LAB82_PLANTCategory .
        OPTIONAL {?BIOAGRESSORS_LAB82_PLANTCategory rdfs:label ?BIOAGRESSORS_LAB1_PLANT .}}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/MYCOSPHAERELLA_GRAMINICOLA> ?BIOAGRESSORS_LAB1_MYCOSPHAERELLA_GRAMINICOLA .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/DELIA_RADICUM> ?BIOAGRESSORS_LAB1_DELIA_RADICUM .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/NUMBER_OF_STEMS> ?BIOAGRESSORS_LAB82_NUMBER_OF_STEMS .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/PLASMODIOPHORA_BRASSICAE> ?BIOAGRESSORS_LAB1_PLASMODIOPHORA_BRASSICAE .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/NUMBER_OF_STEMS_PER_PLANT> ?BIOAGRESSORS_LAB82_NUMBER_OF_STEMS_PER_PLANT .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/NUMBER_OF_LIVING_LEAVES> ?BIOAGRESSORS_LAB82_NUMBER_OF_LIVING_LEAVES .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/FUSARIUM_GRAMINEARUM> ?BIOAGRESSORS_LAB1_FUSARIUM_GRAMINEARUM .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/PYRENOPEZZIZA_BRASSICAE> ?BIOAGRESSORS_LAB1_PYRENOPEZZIZA_BRASSICAE .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/PUCCINIA_RECONDITA> ?BIOAGRESSORS_LAB1_PUCCINIA_RECONDITA .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/NUMBER_OF_LIVING_%20LEAVES> ?BIOAGRESSORS_LAB82_NUMBER_OF_LIVING_LEAVES .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/PLANT_HEIGHT> ?BIOAGRESSORS_LAB82_PLANT_HEIGHT .}
    OPTIONAL {?BIOAGRESSORS_LAB82_uri <http://askomics.org/data/SCAPTOMYZA_FLAVA> ?BIOAGRESSORS_LAB1_SCAPTOMYZA_FLAVA .}



}
